# Django Tools
from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point
from django.utils import timezone

# Models
from users.models import User
from locations.models import Location
from chat.models import Chat, ChatParticipant, Message
from posts.models import Found_post, Lost_post, Surrender_custody_pets

# Etc.
from petoria.settings import LOCAL_APPS
from datetime import UTC
from faker import Faker
import random, string


# -----------------------------------------
# Helpers
# -----------------------------------------


def iran_random_point():
    """Return a random lat/lng inside Iran's bounding box."""
    # Approx bounding box of Iran (not perfectly accurate but good enough)
    min_lat, max_lat = 25.0, 40.0
    min_lng, max_lng = 44.0, 63.0

    lat = random.uniform(min_lat, max_lat)
    lng = random.uniform(min_lng, max_lng)
    return Point(lng, lat)  # GeoDjango uses (x=lng, y=lat)


def random_phone():
    return "+98" + "".join(random.choice(string.digits) for _ in range(9))


# -----------------------------------------
# Seeder Command
# -----------------------------------------

ARGUABLE_APPS = [app_name for app_name in LOCAL_APPS if app_name != "petoria"]


class Command(BaseCommand):
    """Seed the database with sample users, posts, chats, and locations."""

    _faker = Faker()
    _default = 5

    def add_arguments(self, parser):

        assert len({model_name[0] for model_name in ARGUABLE_APPS}) == len(
            ARGUABLE_APPS
        )  # check whether there's any character conflict
        for model_name in ARGUABLE_APPS:
            parser.add_argument(
                f"--{model_name}",
                f"-{model_name[0]}",
                type=int,
                default=0,
                help="Number of fake {model_name} to generate",
            )

    def handle(self, *args, **kwargs):
        if not any([kwargs[model_name] for model_name in ARGUABLE_APPS]):
            for model_name in ARGUABLE_APPS:
                kwargs[model_name] = self._default

        self.stdout.write(self.style.WARNING("Seeding database...\n"))
        # here we handle whether to make these function files
        self.generate_users(kwargs["users"]) if kwargs["users"] else None
        self.generate_locations(kwargs["locations"]) if kwargs["locations"] else None
        self.generate_chats(kwargs["chat"]) if kwargs["chat"] else None
        self.generate_posts(kwargs["posts"]) if kwargs["posts"] else None
        self.stdout.write(self.style.SUCCESS("\nSeeding complete!"))

    # -----------------------------------------
    # Actual Generat(or|ing) Commands
    # -----------------------------------------

    def generate_users(self, count):
        # self.stdout.write(self.style.WARNING("Generating users..."))
        self.stdout.write("Generating users...")
        for _ in range(count):
            fu = self._faker.profile()  # fake user generated by Faker
            full_name = str(fu["name"]).split()
            date_joined = self._faker.past_datetime(tzinfo=UTC)
            User.objects.create_user(
                username=str(fu["username"]),
                is_superuser=False,
                is_staff=False,
                is_active=random.choice([True, False]),
                bio=self._faker.bs(),
                email_notifications=random.choice([True, False]),
                date_joined=date_joined,
                last_login=self._faker.date_time_between(date_joined, tzinfo=UTC),
                profile_picture=self._faker.image_url(),
                location=self._generate_single_location(),
                email=str(fu["mail"]),
                password=self._faker.password(),
                phone=random_phone(),
                first_name=full_name[0],
                last_name=full_name[-1],
                dis_email_verified=True,
            )

        self.stdout.write(self.style.SUCCESS(f"Created {count} users."))

    def generate_posts(self, count):
        self.stdout.write(self.style.WARNING("Generating posts..."))
        for _ in range(count):
            i = self._faker.random_int()
            unique_loc = self._generate_single_location()
            pet_type = random.choice([True, False])
            pet_gender = random.choice(["male", "female"])
            Lost_post.objects.create(
                user=random.choice(User.objects.all()),
                location=unique_loc,
                title=f"Lost {pet_type}",
                description=self._faker.bs(),
                pet_type=pet_type,
                pet_name="Milo",
                pet_age=random.randint(2, 12),
                pet_sex=pet_gender,
                breed="British Shorthair",
                Specific_symptoms="Limping" + self._faker.bs(),
                contact_phone=random.choice([True, False]),
                contact_email=random.choice([True, False]),
                status="active",
                # images=None,
                created_at=timezone.now(),
                updated_at=timezone.now(),
                lost_time=timezone.now(),
            )

            unique_loc = self._generate_single_location()
            Found_post.objects.create(
                user=random.choice(User.objects.all()),
                location=unique_loc,
                title="Found Small Dog",
                description=self._faker.bs(),
                pet_type=pet_type,
                pet_sex=pet_gender,
                pet_name="Unknown",
                pet_age=random.randint(2, 15),
                breed=self._faker.words(3),
                Specific_symptoms="Wearing a red collar" + self._faker.bs(),
                contact_phone=random.choice([True, False]),
                contact_email=random.choice([True, False]),
                status="active",
                # images=None,
                created_at=timezone.now(),
                updated_at=timezone.now(),
            )

            unique_loc = self._generate_single_location()
            Surrender_custody_pets.objects.create(
                title=f"Adoption Post #{random.randint(1,len(User.objects.all()))}",
                description=self._faker.bs(),
                user=random.choice(User.objects.all()),
                location=unique_loc,
                pet_type=pet_type,
                pet_sex=pet_gender,
                pet_name=f"{str(pet_type).capitalize()}{random.randint(1,len(User.objects.all()))}",
                contact_phone=random.choice([True, False]),
            )

        for case in ["lost", "found", "surSurrender/custody"]:
            self.stdout.write(
                self.style.SUCCESS(
                    f"Created {count} {case} posts + one new (unique) location for each"
                )
            )

    def _generate_single_location(self):
        return Location.objects.create(
            point=iran_random_point(),
            district=f"Sample Address {iran_random_point()}",
            city="Tehran",
            country="Iran",
        )

    def generate_locations(self, count):
        self.stdout.write(self.style.WARNING("Generating locations..."))
        for _ in range(count):
            self._generate_single_location()

        self.stdout.write(self.style.SUCCESS(f"Created {count} locations."))

    def generate_chats(self, count):
        self.stdout.write(self.style.WARNING("Generating chats..."))
        users = list(User.objects.all())
        for _ in range(count):
            u1, u2 = random.sample(users, 2)  # type: ignore
            chat = Chat.objects.create()
            ChatParticipant.objects.create(chat=chat, user=u1)
            ChatParticipant.objects.create(chat=chat, user=u2)

            # Messages inside each chat
            for _ in range(random.randint(3, 15)):
                Message.objects.create(
                    chat=chat,
                    sender=random.choice([u1, u2]),
                    content=self._faker.bs(),
                    timestamp=timezone.now(),
                )

        self.stdout.write(self.style.SUCCESS(f"Created {count} chats."))
