# Django Tools
from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point
from django.utils import timezone

# Models
from users.models import User
from locations.models import Location
from chat.models import Chat, ChatParticipant, Message
from posts.models import Found_post, Lost_post, Surrender_custody_pets

# Etc.
from petoria.settings import LOCAL_APPS
from datetime import UTC
from faker import Faker
import random, string


# -----------------------------------------
# Helpers
# -----------------------------------------


def iran_random_point():
    """Return a random lat/lng inside Iran's bounding box."""
    # Approx bounding box of Iran (not perfectly accurate but good enough)
    min_lat, max_lat = 25.0, 40.0
    min_lng, max_lng = 44.0, 63.0

    lat = random.uniform(min_lat, max_lat)
    lng = random.uniform(min_lng, max_lng)
    return Point(lng, lat)  # GeoDjango uses (x=lng, y=lat)


def random_phone():
    return "+98" + "".join(random.choice(string.digits) for _ in range(9))


# -----------------------------------------
# Seeder Command
# -----------------------------------------

ARGUABLE_APPS = [app_name for app_name in LOCAL_APPS if app_name != "petoria"]


class Command(BaseCommand):
    """Seed the database with sample users, posts, chats, and locations."""

    _faker = Faker()

    def add_arguments(self, parser):
        for model_name in ARGUABLE_APPS:
            parser.add_argument(
                f"--{model_name}",
                f"-{model_name[0]}",
                type=int,
                default=5,
                help="Number of fake {model_name} to generate",
            )

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING("Seeding database..."))
        self.generate_users(kwargs["users"])
        self.generate_locations(kwargs["locations"])
        self.generate_posts(kwargs["posts"])
        self.generate_chats(kwargs["chat"])
        self.stdout.write(self.style.SUCCESS("\nSeeding complete!"))

    # -----------------------------------------
    # Actual Generat(or|ing) Commands
    # -----------------------------------------

    def generate_users(self, count):
        for _ in range(count):
            fu = self._faker.profile()  # fake user generated by Faker
            full_name = str(fu["name"]).split()
            date_joined = self._faker.past_datetime(tzinfo=UTC)
            User.objects.create_user(
                username=str(fu["username"]),
                is_superuser=False,
                is_staff=False,
                is_active=random.choice([True, False]),
                bio=self._faker.bs(),
                email_notifications=random.choice([True, False]),
                date_joined=date_joined,
                last_login=self._faker.date_time_between(date_joined, tzinfo=UTC),
                profile_picture=self._faker.image_url(),
                email=str(fu["mail"]),
                password=self._faker.password(),
                phone=random_phone(),
                first_name=full_name[0],
                last_name=full_name[-1],
            )

        self.stdout.write(self.style.SUCCESS(f"Created {count} users."))

    def generate_posts(self, count):
        for _ in range(count):
            i = self._faker.random_int()
            unique_loc = self._generate_single_location()
            Found_post.objects.create(
                title=f"Lost Pet #{i}",
                description="A sample lost pet post.",
                user=random.choice(User.objects.all()),
                location=unique_loc,
                pet_type="cat",
                pet_sex="male",
                pet_name=f"Cat{i}",
                contact_phone=random_phone(),
            )

            unique_loc = self._generate_single_location()
            Surrender_custody_pets.objects.create(
                title=f"Adoption Post #{i}",
                description="A sample adoption post.",
                user=random.choice(User.objects.all()),
                location=unique_loc,
                pet_type="dog",
                pet_sex="female",
                pet_name=f"Dog{i}",
                contact_phone=random_phone(),
            )
        for case in ["lostfound", "adaption"]:
            self.stdout.write(
                self.style.SUCCESS(
                    f"Created {count} {case} posts + one new (unique) location for each"
                )
            )

    def _generate_single_location(self):
        return Location.objects.create(
            point=iran_random_point(),
            address=f"Sample Address {iran_random_point()}",
            city="Tehran",
            country="Iran",
        )

    def generate_locations(self, count):
        for _ in range(count):
            self._generate_single_location()

        self.stdout.write(self.style.SUCCESS(f"Created {count} locations."))

    def generate_chats(self, count):
        users = list(User.objects.all())
        for _ in range(count):
            u1, u2 = random.sample(users, 2)  # type: ignore
            chat = Chat.objects.create()
            ChatParticipant.objects.create(chat=chat, user=u1)
            ChatParticipant.objects.create(chat=chat, user=u2)

            # Messages inside each chat
            for _ in range(random.randint(3, 15)):
                Message.objects.create(
                    chat=chat,
                    sender=random.choice([u1, u2]),
                    content=self._faker.bs(),
                    timestamp=timezone.now(),
                )

        self.stdout.write(self.style.SUCCESS(f"Created {count} chats."))
