# Django Tools
from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point
from django.utils import timezone

# Models
from users.models import User
from locations.models import Location
from chat.models import Chat, ChatParticipant, Message
from posts.models import FoundPost, LostPost, SurrenderCustodyPet, PetAge

# Etc.
from petoria.settings import LOCAL_APPS
from datetime import UTC
from faker import Faker
import random, string
from posts.enums import PetType


# -----------------------------------------
# Helpers
# -----------------------------------------


def iran_random_point():
    """Return a random lat/lng inside Iran's bounding box."""
    # Approx bounding box of Iran (not perfectly accurate but good enough)
    min_lat, max_lat = 25.0, 40.0
    min_lng, max_lng = 44.0, 63.0

    lat = random.uniform(min_lat, max_lat)
    lng = random.uniform(min_lng, max_lng)
    return Point(lng, lat)  # GeoDjango uses (x=lng, y=lat)


def random_phone():
    return "+98" + "".join(random.choice(string.digits) for _ in range(9))


# -----------------------------------------
# Seeder Command
# -----------------------------------------

ARGUABLE_APPS = [app_name for app_name in LOCAL_APPS if app_name != "petoria"]


class Command(BaseCommand):
    """Seed the database with sample users, posts, chats, and locations."""

    _faker = Faker()

    def add_arguments(self, parser):
        parser.add_argument(
            "COUNT",
            nargs="?",
            type=int,
            default=5,
            help="generate COUNT many of each model (using any other count-specifying flag overrides this argument)",
        )

        assert len({model_name[0] for model_name in ARGUABLE_APPS}) == len(
            ARGUABLE_APPS
        )  # check whether there's any character conflict
        for model_name in ARGUABLE_APPS:
            parser.add_argument(
                f"--{model_name}",
                f"-{model_name[0]}",
                type=int,
                default=0,
                help=f"Number of fake sample objects for {model_name}",
            )

    def handle(self, *args, **kwargs):
        if not any([kwargs[model_name] for model_name in ARGUABLE_APPS]):
            for model_name in ARGUABLE_APPS:
                kwargs[model_name] = kwargs["COUNT"] if kwargs["COUNT"] else 5

        self.stdout.write("Seeding database...\n\n")
        # here we handle whether to make these function calls
        # fmt:off
        self.generate_users(kwargs["users"]) if kwargs["users"] else None
        next(self.generate_locations(kwargs["locations"])) if kwargs["locations"] else None
        self.generate_chats(kwargs["chat"]) if kwargs["chat"] else None
        self.generate_posts(kwargs["posts"]) if kwargs["posts"] else None
        self.stdout.write(self.style.SUCCESS("\nSeeding complete!"))
        # fmt:on

    # -----------------------------------------
    # Actual Generat(or|ing) Commands
    # -----------------------------------------

    def generate_users(self, count):
        self.stdout.write(self.style.WARNING(f"Generating {count} users..."))
        for _ in range(count):
            fu = self._faker.profile()  # fake user generated by Faker
            full_name = str(fu["name"]).split()
            date_joined = self._faker.past_datetime(tzinfo=UTC)
            User.objects.create_user(
                username=str(fu["username"]),
                is_superuser=False,
                is_staff=False,
                is_active=random.choice([True, False]),
                bio=self._faker.bs(),
                email_notifications=random.choice([True, False]),
                date_joined=date_joined,
                last_login=self._faker.date_time_between(date_joined, tzinfo=UTC),
                profile_picture=self._faker.image_url(),
                location=next(self.generate_locations(1, False)),
                email=str(fu["mail"]),
                password='password',
                phone=random_phone(),
                first_name=full_name[0],
                last_name=full_name[-1],
                is_email_verified=True,
            )

        self.stdout.write(self.style.SUCCESS(f"Created {count} users."))

    def generate_posts(self, count):
        self.stdout.write(
            self.style.WARNING(f"Generating {count} posts (of each type)...")
        )
        for _ in range(count):
            i = self._faker.random_int()
            unique_loc = next(self.generate_locations(1, False))
            pet_type = random.choice([PetType.CAT, PetType.DOG])
            pet_gender = random.choice(["male", "female"])
            lost_age = PetAge.objects.create(
                years=random.randint(0, 12),
                months=random.randint(0, 11),
            )
            LostPost.objects.create(
                user=random.choice(User.objects.all()),
                location=unique_loc,
                title=f"Lost {pet_type}",
                description=self._faker.bs(),
                pet_type=pet_type,
                pet_name="Milo",
                pet_age=lost_age,
                pet_sex=pet_gender,
                breed="British Shorthair",
                Specific_symptoms="Limping" + self._faker.bs(),
                contact_phone=random.choice([True, False]),
                contact_email=random.choice([True, False]),
                status="active",
                # images=None,
                created_at=timezone.now(),
                updated_at=timezone.now(),
                lost_time=timezone.now(),
            )

            unique_loc = next(self.generate_locations(1, False))
            found_age = PetAge.objects.create(
                years=random.randint(0, 15),
                months=random.randint(0, 11),
            )
            FoundPost.objects.create(
                user=random.choice(User.objects.all()),
                location=unique_loc,
                title="Found Small Dog",
                description=self._faker.bs(),
                pet_type=pet_type,
                pet_sex=pet_gender,
                pet_name="Unknown",
                pet_age=found_age,
                breed=self._faker.words(3),
                Specific_symptoms="Wearing a red collar" + self._faker.bs(),
                contact_phone=random.choice([True, False]),
                contact_email=random.choice([True, False]),
                status="active",
                # images=None,
                created_at=timezone.now(),
                updated_at=timezone.now(),
            )

            unique_loc = next(self.generate_locations(1, False))
            custody_age = PetAge.objects.create(
                years=random.randint(0, 12),
                months=random.randint(0, 11),
            )
            SurrenderCustodyPet.objects.create(
                title=f"Adoption Post #{random.randint(1,len(User.objects.all()))}",
                description=self._faker.bs(),
                user=random.choice(User.objects.all()),
                location=unique_loc,
                pet_type=pet_type,
                pet_sex=pet_gender,
                pet_name=f"{str(pet_type).capitalize()}{random.randint(1,len(User.objects.all()))}",
                pet_age=custody_age,
                contact_phone=random.choice([True, False]),
            )

        for case in ["lost", "found", "surSurrender/custody"]:
            self.stdout.write(
                self.style.SUCCESS(
                    f"Created {count} {case} posts + one new (unique) location for each"
                )
            )

    def generate_locations(self, count, do_log=True):
        # fmt:off
        self.stdout.write(self.style.WARNING(f"Generating {count} locations...")) if do_log else None
        try:
            for _ in range(count):
                yield Location.objects.create(
                point=iran_random_point(),
                district=f"Sample Address {iran_random_point()}",
                city="Tehran",
                country="Iran",
            )
        except Exception as err:
            raise err
        finally:
            self.stdout.write(self.style.SUCCESS(f"Created {count} locations.")) if do_log else None
        # fmt:on

    def generate_chats(self, count):
        self.stdout.write(self.style.WARNING(f"Generating {count} chats..."))
        users = list(User.objects.all())
        for _ in range(count):
            u1, u2 = random.sample(users, 2)  # type: ignore
            chat = Chat.objects.create()
            ChatParticipant.objects.create(chat=chat, user=u1)
            ChatParticipant.objects.create(chat=chat, user=u2)

            # Messages inside each chat
            for _ in range(random.randint(3, 15)):
                Message.objects.create(
                    chat=chat,
                    sender=random.choice([u1, u2]),
                    content=self._faker.bs(),
                    timestamp=timezone.now(),
                )

        self.stdout.write(self.style.SUCCESS(f"Created {count} chats."))
