# Generated by Django 5.2.8 on 2025-11-14 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_participants_chat_members_remove_message_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=django.db.models.deletion.SET_NULL, null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
