# Generated by Django 5.2.8 on 2025-11-14 19:34

import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=django.db.models.query.QuerySet.none, null=True, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
