# Generated by Django 5.2.8 on 2025-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('story', models.TextField(max_length=5000)),
                ('story_type', models.CharField(choices=[('lost', 'Lost Pet'), ('found', 'Found Pet'), ('surrender', 'Surrender/Custody')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
