from django.core.management.base import BaseCommand
from users.models import User
from datetime import UTC
from faker import Faker
import random, string


def random_phone():
    return "+98" + "".join(random.choice(string.digits) for _ in range(9))


class Command(BaseCommand):
    """Seed the database with sample users, posts, chats, and locations."""

    def add_arguments(self, parser):
        parser.add_argument(
            "-u",
            "--users",
            type=int,
            default=5,
            help="Number of fake users to generate",
        )

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING("Seeding database..."))
        count = kwargs["users"]
        fake = Faker()
        for _ in range(count):
            fu = fake.profile()  # fake user generated by Faker
            full_name = str(fu["name"]).split()
            date_joined = fake.past_datetime(tzinfo=UTC)
            User.objects.create_user(
                username=str(fu["username"]),
                is_superuser=False,
                is_staff=False,
                is_active=random.choice([True, False]),
                bio=fake.bs(),
                email_notifications=random.choice([True, False]),
                date_joined=date_joined,
                last_login=fake.date_time_between(date_joined,tzinfo=UTC),
                profile_picture=fake.image_url(),
                email=str(fu["mail"]),
                password=fake.password(),
                phone=random_phone(),
                first_name=full_name[0],
                last_name=full_name[-1],
            )

        self.stdout.write(self.style.SUCCESS(f"Created {count} users."))
        self.stdout.write(self.style.SUCCESS("\nSeeding complete!"))
