from django.core.management.base import BaseCommand
from users.models import User
from faker import Faker
import random, string

# -----------------------------------------
# Helpers
# -----------------------------------------


def random_phone():
    return "+98" + "".join(random.choice(string.digits) for _ in range(9))


# -----------------------------------------
# Seeder Command
# -----------------------------------------


class Command(BaseCommand):
    """Seed the database with sample users, posts, chats, and locations."""

    def add_arguments(self, parser):
        parser.add_argument(
            "-u",
            "--users",
            type=int,
            default=10,
            help="Number of fake users to generate",
        )

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.WARNING("Seeding database..."))

        # -------------------------------------
        # USERS
        # -------------------------------------
        count = kwargs["users"]
        fake = Faker()
        for _ in range(count):
            fu = fake.profile()  # fake user generated by Faker
            fake_user = User.objects.create_user(
                username=fu["username"],
                email=fu["mail"],
                password=fake.password(),
                phone=random_phone(),
                first_name=fu["name"].split()[0],
                last_name=fu["name"].split()[-1],
            )

        self.stdout.write(self.style.SUCCESS(f"Created {count} users."))
        self.stdout.write(self.style.SUCCESS("\nSeeding complete!"))
