# Generated by Django 5.2.8 on 2025-11-13 11:34

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_delete_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_pics/default_avatar.png', help_text='User profile photo - helps build trust in the community', null=True, upload_to='profile_pics/'),
        ),
    ]
