# Generated by Django 5.2.8 on 2025-11-20 17:13

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_token_c80ef6_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_user_id_8f79bf_idx',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.CharField(default=users.models.generate_6_digit_code, max_length=6),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
