# Generated by Django 5.2.8 on 2025-12-06 01:46

import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_token_c80ef6_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='users_email_user_id_8f79bf_idx',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.CharField(default=users.models.generate_6_digit_code, max_length=6),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dis_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications '),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone for urgent pet communications', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_pics/default_avatar.png', help_text='User profile photo', null=True, upload_to='profile_pics/'),
        ),
    ]
