# Generated by Django 5.2.8 on 2025-11-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLocation',
        ),
    ]
