# Generated by Django 5.2.8 on 2025-11-13 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('posts', '0002_delete_postlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clear, descriptive title for the post', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pet and situation', max_length=5000)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the post')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], default='other', help_text='Type of pet', max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Gender of the pet', max_length=10)),
                ('pet_name', models.CharField(blank=True, help_text='Name of the pet (if known)', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone must start with 09 and contain 11 digits total.', regex='^09[0-9]{9}$')])),
                ('contact_email', models.EmailField(blank=True, help_text='Email for direct contact (optional)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', help_text='Current status of the post', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostFoundPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clear, descriptive title for the post', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pet and situation', max_length=5000)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs for the post')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], default='other', help_text='Type of pet', max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Gender of the pet', max_length=10)),
                ('pet_name', models.CharField(blank=True, help_text='Name of the pet (if known)', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone must start with 09 and contain 11 digits total.', regex='^09[0-9]{9}$')])),
                ('contact_email', models.EmailField(blank=True, help_text='Email for direct contact (optional)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', help_text='Current status of the post', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
