# Generated by Django 5.2.8 on 2025-11-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptionpost',
            old_name='sex',
            new_name='pet_sex',
        ),
        migrations.RenameField(
            model_name='lostfoundpost',
            old_name='sex',
            new_name='pet_sex',
        ),
    ]
