# Generated by Django 5.2.8 on 2025-12-06 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0002_remove_location_address_remove_location_created_at_and_more'),
        ('posts', '0004_rename_sex_adaptionpost_pet_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfoundpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lostfoundpost',
            name='user',
        ),
        migrations.CreateModel(
            name='Found_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Clear, descriptive title for the post', max_length=120, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pet and situation', max_length=5000)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], default='other', help_text='Select the type of pet.', max_length=20)),
                ('pet_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Select the gender of the pet.', max_length=10)),
                ('pet_name', models.CharField(blank=True, help_text="Pet's name (optional).", max_length=100, null=True)),
                ('pet_age', models.CharField(blank=True, help_text='Age of the pet.', max_length=100, null=True)),
                ('breed', models.CharField(blank=True, help_text='Breed (optional).', max_length=100)),
                ('Specific_symptoms', models.CharField(blank=True, help_text='Color or markings (optional).', max_length=100)),
                ('contact_phone', models.BooleanField(default=False, help_text='Show phone')),
                ('contact_email', models.BooleanField(default=False, help_text='Show email ')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', help_text='Select the current status of the post.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_time', models.DateTimeField(blank=True, help_text='When the pet was found.', null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lost_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Clear, descriptive title for the post', max_length=120, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pet and situation', max_length=5000)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], default='other', help_text='Select the type of pet.', max_length=20)),
                ('pet_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Select the gender of the pet.', max_length=10)),
                ('pet_name', models.CharField(blank=True, help_text="Pet's name (optional).", max_length=100, null=True)),
                ('pet_age', models.CharField(blank=True, help_text='Age of the pet.', max_length=100, null=True)),
                ('breed', models.CharField(blank=True, help_text='Breed (optional).', max_length=100)),
                ('Specific_symptoms', models.CharField(blank=True, help_text='Color or markings (optional).', max_length=100)),
                ('contact_phone', models.BooleanField(default=False, help_text='Show phone')),
                ('contact_email', models.BooleanField(default=False, help_text='Show email ')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', help_text='Select the current status of the post.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lost_time', models.DateTimeField(blank=True, help_text='When the pet was lost.', null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Surrender_custody_pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Clear, descriptive title for the post', max_length=120, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the pet and situation', max_length=5000)),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_animal', 'Small Animal'), ('other', 'Other')], default='other', help_text='Select the type of pet.', max_length=20)),
                ('pet_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text='Select the gender of the pet.', max_length=10)),
                ('pet_name', models.CharField(blank=True, help_text="Pet's name (optional).", max_length=100, null=True)),
                ('pet_age', models.CharField(blank=True, help_text='Age of the pet.', max_length=100, null=True)),
                ('breed', models.CharField(blank=True, help_text='Breed (optional).', max_length=100)),
                ('Specific_symptoms', models.CharField(blank=True, help_text='Color or markings (optional).', max_length=100)),
                ('contact_phone', models.BooleanField(default=False, help_text='Show phone')),
                ('contact_email', models.BooleanField(default=False, help_text='Show email ')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', help_text='Select the current status of the post.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diseases', models.TextField(blank=True, help_text='Known diseases or health issues.')),
                ('has_birth_certificate', models.BooleanField(default=False, help_text='Does the pet have a birth certificate?')),
                ('vaccination', models.BooleanField(default=False)),
                ('steriliz', models.BooleanField(default=False)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AdaptionPost',
        ),
        migrations.DeleteModel(
            name='LostFoundPost',
        ),
    ]
