# Generated by Django 5.2.8 on 2025-11-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0004_rename_sex_adaptionpost_pet_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptionpost',
            name='images',
        ),
        migrations.RemoveField(
            model_name='lostfoundpost',
            name='images',
        ),
        migrations.AlterField(
            model_name='adaptionpost',
            name='title',
            field=models.CharField(help_text='Clear, descriptive title for the post', max_length=140),
        ),
        migrations.AlterField(
            model_name='lostfoundpost',
            name='title',
            field=models.CharField(help_text='Clear, descriptive title for the post', max_length=140),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
