# Generated by Django 5.2.8 on 2025-11-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_sex_adaptionpost_pet_sex_and_more'),
    ]

    operations = [
    ]
